### ISSUE TITLE
Check the template calls

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-account#1]
As explained [here](https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Week-by-Week-Activity#check-the-templateurl-calls-no-html-template-should-be-served-from-the-backend), no template should be sent from the backend.

Make sure that every template is served by the frontend.

**Comment by asmaNode** [comment]
all templateURL is updated in this project
