### ISSUE TITLE
 The "Create indentity" button & My identity (default) are not displayed in Identities tab 

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-account#33]
Reproduce steps:
- Identity is enabled on Admin site 
- Go to https://dev.open-paas.org/ and login
- Go to the SPA URLs: https://dev.open-paas.org/account/
- Select to Identities tab
- Verify issue 

Actual Results: When this tab is opened, there is no information such as My My identity (default) and the button "Create a new identity"  
![image](https://user-images.githubusercontent.com/69950706/90727472-926d8900-e2ed-11ea-9f06-9be9ee0aed64.png)
![image](https://user-images.githubusercontent.com/69950706/90732163-e4fe7380-e2f4-11ea-978d-61e31b823be3.png)

Expected Results:  The "Create indentity" button and  info "My identity(default) is shown in the identity tab

**Comment by pbson** [comment]
At the moment, on https://dev.open-paas.org/, the "My identity" does exist in the identity tab and the button is still not showing. But on local, both the issues isn't there. Could you have a look again? @TuanQA92

**Comment by tlle14** [comment]
> At the moment, on https://dev.open-paas.org/, the "My identity" does exist in the identity tab and the button is shown. On local, both the issues isn't there either. Could you have a look again? @TuanQA92

Hi @pbson 
I don't see identity is shown. Please check 
![image](https://user-images.githubusercontent.com/69950655/92349498-7e54c480-f100-11ea-9444-aac371e47035.png)

**Comment by piavgh** [comment]
![Screenshot 2020-09-08 17:15:46](https://user-images.githubusercontent.com/4060207/92464191-04533700-f1f7-11ea-98d7-9b681f77a515.png)

I can not reproduce this issue with my account on dev server also
