### ISSUE TITLE
List of users are not displayed in the "followers" & "Followings" tab 

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-account#34]
Actual Result: There is a user in the "followers" and "followings" tab.  However, When accessing these tabs, the list of users is not displayed. 
![image](https://user-images.githubusercontent.com/69950706/90759229-5ac10a00-e30a-11ea-87dd-251ffc4f7acb.png)

Expected result

Please investigate this, the list of users should be shown.

Steps

1. Navigate to account module
2. Select to the "Followers" & "Followings" tab 
3. Verify issue 

Environment

- Test link: https://dev.open-paas.org/
- Browser: Ubuntu Firefox 79.0 & Ubuntu Chrome 74.0

**Comment by tlle14** [comment]
Will be removed in this ticket https://github.com/OpenPaaS-Suite/esn-frontend-account/issues/65
