### ISSUE TITLE
Cannot access Account module

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-account#36]
**Actual Result**

Cannot access Account module
![image](https://user-images.githubusercontent.com/69950655/91004133-8c352080-e5fd-11ea-8f22-ef6df16df5ae.png)

**Expected result**
Account module should be accessible

**Environment**
Browsers on Ubuntu

**Comment by huy-ta** [comment]
@asmaNode Please write a simple DoD like [this one](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/74#issuecomment-678178312) and then @ one of the members of the QA team (preferrably the author of the issue) so that he/she can receive a mail notification.

**Comment by tlle14** [comment]
Thank @asmaNode 

Retest pass! I can access the Account module now. 

![image](https://user-images.githubusercontent.com/69950655/92067150-ce185080-edcd-11ea-9151-11788d18f381.png)
