### ISSUE TITLE
Unable to logout from Admin SPA

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-account#43]
**Actual Result**

Cannot logout from the Admin account, it generates an error log.

![logout](https://user-images.githubusercontent.com/69950655/91383748-17f5b980-e857-11ea-8ee1-239c483cffce.gif)

![image](https://user-images.githubusercontent.com/69950655/91383737-11674200-e857-11ea-84d0-7ae21c9c3d88.png)

**Expected result**

Admin should be able to logout

**Environment**

Browsers on Ubuntu

**Comment by chamerling** [comment]
This is fixed in OpenPaaS-Suite/esn#20 which is not merged yet

**Comment by tlle14** [comment]
> This is fixed in [OpenPaaS-Suite/esn#20](https://github.com/OpenPaaS-Suite/esn/issues/20) which is not merged yet

Please tag me when it ready to be tested. Thank you!

**Comment by MichaelBailly** [comment]
can not reproducce
