### ISSUE TITLE
The account SPA is missing some translations

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-account#44]
See the screenshot below, please also check for the other languages as well.

![account-no-vi-translation](https://user-images.githubusercontent.com/24670327/91416335-716ee000-e879-11ea-9fda-095481dc14b9.png)

**Comment by huy-ta** [comment]
Also, the "Save" button is incorrectly translated into Vietnamese, it should be "Lưu", not "Tiết kiệm".

**Comment by rezk2ll** [comment]
> Also, the "Save" button is incorrectly translated into Vietnamese, it should be "Lưu", not "Tiết kiệm". @rezk2ll Can you also fix that too?

noted
