### ISSUE TITLE
Account don't support search advanced provider so we need to hide the component

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-account#46]
### CURRENT

search advanced component is display but we currently don't support search advanced provider so search don't work.

![Capture d’écran de 2020-08-27 11-49-06](https://user-images.githubusercontent.com/11298249/91425402-5ee5ae00-e85b-11ea-98a6-342638a5ec1b.png)

### EXPECTED

Hide search advanced component

![Capture d’écran de 2020-08-27 11-49-17](https://user-images.githubusercontent.com/11298249/91425399-5ee5ae00-e85b-11ea-9112-357b71e787ba.png)

### TO DO 

- [ ] If no search advanced provider, we need to hide the component

**Comment by tuanlc** [comment]
I don't think so. The global search box should be always there.
1. Consistent  UX/UI for header among SPAs
2. Even there is no search for account for now, users still need to search other resources

cc @MichaelBailly @chamerling

**Comment by chamerling** [comment]
We must be consistent and so we must keep it. USer needs to access to the search from any SPA

**Comment by fabienmoyon** [comment]
I didn't create issue for nothing!

We currently don't have search provider for `Account` so search is unusable and do nothing. So we need to hide the search and we could show it again like it's specialize on this enhancement https://github.com/OpenPaaS-Suite/esn-frontend-account/issues/47

**Comment by piavgh** [comment]
## DoD:

In account SPA:
- Desktop: the global search bar does not appear
- Mobile: the magnifying glass icon does not appear

**Comment by tlle14** [comment]
Thank @piavgh 

Retest pass on DEV environment

![image](https://user-images.githubusercontent.com/69950655/94423445-da1be600-01b2-11eb-912b-80eeb0a8a675.png)
