### ISSUE TITLE
Unable to update profile picture

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-account#57]
**Actual Result**

After uploading a profile picture, click "save" button will throw an error, and the profile picture cannot be saved. 

The portrait image will overflow the uploading border.

![image](https://user-images.githubusercontent.com/69950655/92071000-d70e1f80-edd7-11ea-8acf-0d6707e24383.png)

**Expected result**

It should be able to upload a profile picture successfully.
While saving, the portrait image should be in the box.

**Steps**

1. Navigate to Accounts page
2. Upload a photo to be a profile picture
3. Click "save" button

**Environment**
Ubuntu desktop

**Comment by tlle14** [comment]
Hi @pbson 

I can upload a profile picture now. **But we should fix the cropping frame to be put in the center of the original picture.** 

![image](https://user-images.githubusercontent.com/69950655/92572961-4fc91c00-f2af-11ea-82ae-3aea162a41d7.png)

**Comment by pbson** [comment]
Fixing the cropping frame to be put in the center of the original picture should be in another issue so I'm gonna close this one.
