### ISSUE TITLE
Unable to setting homepage

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-account#66]
**Actual Result**

On Account > Setting, the user is unable to set Home Page.

- On Production: Other modules aren't displaying on the list

![image](https://user-images.githubusercontent.com/69950655/92568461-6bc9bf00-f2a9-11ea-915f-ee3babe3010d.png)

- On Dev Environment: Home Page selection doesn't display

![image](https://user-images.githubusercontent.com/69950655/92568537-8308ac80-f2a9-11ea-80f3-248620da1a1f.png)

**Expected Result**

User should be able to select a module in OpenPaas to be a Home Page.

**Comment by MichaelBailly** [comment]
This control will be removed temporary, until we have the application discovery service running.
