### ISSUE TITLE
Non-admin users are not able to add/edit/delete their own identities

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-account#67]
Steps:

1. As admin, go to Adminstration >> UnifiedInbox >> enable "Allow users to manage their identities" then Save

2. As non-admin user, refresh his openpaas windows, go to Profile

3. Select Identities tab

Expected result:

User is able to add/edit/delete their own identities

Actual result:

User is not able to do that

**Comment by tuanlc** [comment]
### DoD

The issue was fixed. Users able to edit/delete their identities.

@hantt12 please retest on production

**Comment by tlle14** [comment]
Thank @tuanlc 

Retest pass!
 
Able to create, update and delete the identity:

![image](https://user-images.githubusercontent.com/69950655/92876472-559c3a00-f434-11ea-88ef-d0fcd08a4c9b.png)

![image](https://user-images.githubusercontent.com/69950655/92881477-381d9f00-f439-11ea-90b9-e92c226e7121.png)
