### ISSUE TITLE
Back button on Identities tab does nothing

### ISSUE THREAD

**Issue by tuanlc** [OpenPaaS-Suite/esn-frontend-account#71]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7950991/93445689-479a5d80-f8fb-11ea-9746-b95aca8b96e0.gif)

Propose: remove back button in identities tab like other tabs

**Comment by piavgh** [comment]
## DoD:

The back button in the Identities tab is removed

**Comment by tlle14** [comment]
Thank @piavgh 

Retest pass on DEV platform

![image](https://user-images.githubusercontent.com/69950655/93852986-3a0b1c00-fcdd-11ea-84c9-caa22e5a3972.png)
