### ISSUE TITLE
As an user I can't edit my job

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-account#74]
![editProfil](https://user-images.githubusercontent.com/11298249/94271770-5eb3fd80-ff42-11ea-81d3-e1591b95a4e5.png)

**Comment by piavgh** [comment]
As I debug, the reason that the job field is not editable on openpaas.linagora.com is that it's one of the `provisioned fields`. While on localhost or dev.open-paas.org, it's not a provisioned field so I can edit the job.

And it seems this `provisioned fields` are configured on the backend (ldap maybe?)

So there are 2 questions:
1. Is this issue a bug? Or an intention?
2. If it's a bug, how can I set this `provisioned fields` for openpaas.linagora.com?

**Comment by tuanlc** [comment]
AFAI K, This is expected from what we implementation
we do not allow people to edit info which are provisioned from LDAP

**Comment by tuanlc** [comment]
> If it's a bug, how can I set this provisioned fields for openpaas.linagora.com?

As I remember, we have a mapping between ESN user attrs and LDAP user attrs. When provisioning user from LDAP to ESN, it will check if the mapping attrs are provided, if yes, it will prevent users to edit these attrs.

**Comment by tuanlc** [comment]
The question is: Do the `edit job` action is required to allow users to edit?

cc @MichaelBailly @fabienmoyon

**Comment by piavgh** [comment]
> Michael confirmed: the list of fields we map from LDAP to OP at Linagora: main-phone, lastname, firstname, job_title and email. 

=> So this issue is not a bug
